let currentUser=null,currentPage="dashboard",isDark=false;
let vrVisited=new Set(),quizBest=0;
let notifs=[{id:1,text:"3-modul boshlanishiga 2 hafta",time:"Bugun",read:false},{id:2,text:"Rezyumengizga baho: A'lo!",time:"Kecha",read:false}];
let loginRole="student";
const today=new Date().toISOString().slice(0,10);

function getBadges(){
  const maxScore=MODULES.reduce((a,m)=>Math.max(a,m.score||0),0);
  return[
  {id:"a1",title:"Birinchi tahlil",desc:"Dekonstruksiya yaratdingiz",icon:"🔍",check:decon.length>=1,cur:Math.min(decon.length,1),max:1,hint:"Tadqiqotchi daftari → Dekonstruksiya",page:"tahlil"},
  {id:"v5",title:"Lug'at ustasi",desc:concepts.length+"/5 so'z",icon:"📚",check:concepts.length>=5,cur:Math.min(concepts.length,5),max:5,hint:"Tadqiqotchi daftari → Lug'at",page:"tahlil"},
  {id:"d2",title:"Debat yulduzi",desc:debates.length+"/2 debat",icon:"💬",check:debates.length>=2,cur:Math.min(debates.length,2),max:2,hint:"Muloqot maydoni → Debatlar",page:"dialog"},
  {id:"co",title:"Xalqaro aloqa",desc:"COIL muloqot",icon:"🌐",check:coil.length>=1,cur:Math.min(coil.length,1),max:1,hint:"Muloqot maydoni → COIL",page:"dialog"},
  {id:"e3",title:"Refleksiya ustasi",desc:essays.length+"/3 esse",icon:"✍️",check:essays.length>=3,cur:Math.min(essays.length,3),max:3,hint:"Tajriba xazinasi → Esselar",page:"tajriba"},
  {id:"m1",title:"Modul fotihi",desc:"Modul yakunlandi",icon:"🏆",check:MODULES.some(m=>m.status==='done'),cur:MODULES.filter(m=>m.status==='done').length,max:1,hint:"Modullarni yakunlang",page:"dashboard"},
  {id:"p9",title:"Mukammallik",desc:maxScore+"/95 ball",icon:"💎",check:maxScore>=95,cur:Math.min(maxScore,95),max:95,hint:"Modullarda 95+ ball oling",page:"dashboard"},
  {id:"vr",title:"Virtual sayohatchi",desc:vrVisited.size+"/1 joy",icon:"🕶️",check:vrVisited.size>=1,cur:Math.min(vrVisited.size,1),max:1,hint:"VR sayohat sahifasiga kiring",page:"vr"},
  {id:"qm",title:"Viktorina ustasi",desc:"Rekord: "+quizBest+"/"+QUIZ.length,icon:"🎯",check:quizBest===QUIZ.length,cur:quizBest,max:QUIZ.length,hint:"Viktorinada 100% to'plang",page:"quiz"},
  {id:"j7",title:"7 kunlik davomiylik",desc:journal.length+"/7 yozuv",icon:"🔥",check:journal.length>=7,cur:Math.min(journal.length,7),max:7,hint:"Kundalikka 7 ta yozuv yozing",page:"journal"},
]}
function earnedCount(){return getBadges().filter(b=>b.check).length}

/* ══════ AUTH ══════ */
function setLoginRole(r){loginRole=r;document.querySelectorAll('.login-tab').forEach((t,i)=>{t.classList.toggle('active',(r==='student'&&i===0)||(r==='teacher'&&i===1))});document.getElementById('login-email').value=r==='teacher'?'teacher@mail.uz':'sardor@mail.uz'}
function doLogin(){const email=document.getElementById('login-email').value,pass=document.getElementById('login-pass').value,user=USERS.find(u=>u.email===email&&u.password===pass);if(!user){document.getElementById('login-error').style.display='block';return}currentUser=user;document.getElementById('login-screen').style.display='none';document.getElementById('app-screen').style.display='flex';document.getElementById('sb-avatar').textContent=user.avatar;document.getElementById('sb-name').textContent=user.name;document.getElementById('sb-role').textContent=user.role==='teacher'?"O'qituvchi":user.group;buildNav();goTo(user.role==='teacher'?'teacher':'dashboard')}
function doLogout(){currentUser=null;document.getElementById('app-screen').style.display='none';document.getElementById('login-screen').style.display='none';const lp=document.getElementById('landing-screen');if(lp){lp.style.display='';lp.style.opacity='1'}else{document.getElementById('login-screen').style.display='flex'}document.getElementById('login-error').style.display='none'}

/* ══════ NAV ══════ */
function buildNav(){const nav=document.getElementById('sidebar-nav');const isT=currentUser.role==='teacher';const secs=isT?[{s:"Asosiy",items:[{id:"teacher",l:"O'qituvchi paneli",ic:"📋"}]},{s:"Ko'rish",items:[{id:"dashboard",l:"Namuna",ic:"🏠"},{id:"calendar",l:"Kalendar",ic:"📅"}]},{s:"",items:[{id:"profil",l:"Profilim",ic:"👤"}]}]:[{s:"Asosiy",items:[{id:"dashboard",l:"Bosh sahifa",ic:"🏠"}]},{s:"Portfolio",items:[{id:"tahlil",l:"Tadqiqotchi daftari",ic:"📖"},{id:"dialog",l:"Muloqot maydoni",ic:"💬"},{id:"tajriba",l:"Tajriba xazinasi",ic:"⭐"}]},{s:"Qo'shimcha",items:[{id:"gamification",l:"Yutuqlar",ic:"🏆",badge:earnedCount()},{id:"quiz",l:"Viktorina",ic:"🎯"},{id:"journal",l:"Kundalik",ic:"📓"},{id:"calendar",l:"Kalendar",ic:"📅"},{id:"map",l:"Sayohat xaritasi",ic:"🗺️"},{id:"vr",l:"VR sayohat",ic:"🕶️"},{id:"kutubxona",l:"Kutubxona",ic:"📚"}]},{s:"",items:[{id:"profil",l:"Profilim",ic:"👤"}]}];
let h='';secs.forEach(s=>{if(s.s)h+=`<div class="sb-label">${s.s}</div>`;s.items.forEach(i=>{h+=`<div class="nav-item ${currentPage===i.id?'active':''}" onclick="goTo('${i.id}')"><span class="ni-icon">${i.ic}</span>${i.l}${i.badge?`<span class="nav-badge">${i.badge}</span>`:''}</div>`})});nav.innerHTML=h}
function goTo(p){currentPage=p;document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));const el=document.getElementById('pg-'+p);if(el)el.classList.add('active');buildNav();closeSidebar();const titles={dashboard:"Bosh sahifa",tahlil:"Tadqiqotchi daftari",dialog:"Muloqot maydoni",tajriba:"Tajriba xazinasi",gamification:"Yutuqlar",quiz:"Viktorina",journal:"Kundalik",calendar:"Kalendar",map:"Sayohat xaritasi",vr:"VR sayohat",kutubxona:"Kutubxona",teacher:"O'qituvchi paneli",profil:"Profilim"};document.getElementById('page-title').textContent=titles[p]||p;const R={dashboard:renderDashboard,tahlil:renderTahlil,dialog:renderDialog,tajriba:renderTajriba,gamification:renderGamification,quiz:renderQuiz,journal:renderJournal,calendar:renderCalendar,map:renderMap,vr:renderVR,kutubxona:renderKutubxona,teacher:renderTeacher,profil:renderProfil};if(R[p])R[p]()}

/* ══════ UI HELPERS ══════ */
function toggleSidebar(){document.getElementById('sidebar').classList.toggle('open');document.getElementById('sb-overlay').classList.toggle('active')}
function closeSidebar(){document.getElementById('sidebar').classList.remove('open');document.getElementById('sb-overlay').classList.remove('active')}
function toggleTheme(){isDark=!isDark;document.documentElement.setAttribute('data-theme',isDark?'dark':'light');document.getElementById('theme-btn').textContent=isDark?'☀️':'🌙'}
function toggleNotifs(){document.getElementById('notif-panel').classList.toggle('show');renderNotifs()}
function renderNotifs(){document.getElementById('notif-list').innerHTML=notifs.map(n=>`<div style="padding:14px 18px;border-bottom:1px solid var(--border-subtle);font-size:12px;opacity:${n.read?.5:1};transition:opacity .2s"><div style="font-weight:${n.read?400:600};color:var(--text-primary)">${n.text}</div><div style="font-size:10px;color:var(--text-muted);margin-top:3px">${n.time}</div></div>`).join('');const c=notifs.filter(n=>!n.read).length;document.getElementById('notif-dot').style.display=c?'block':'none'}
function showToast(b){const t=document.getElementById('badge-toast');t.innerHTML=`<div style="font-size:40px;animation:popIn .5s var(--ease-bounce)">${b.icon}</div><div><div style="font-size:10px;font-weight:800;letter-spacing:1.5px;background:linear-gradient(90deg,var(--accent-amber),var(--accent-coral));-webkit-background-clip:text;-webkit-text-fill-color:transparent">YANGI YUTUQ!</div><div style="font-size:15px;font-weight:700;font-family:var(--ff-display)">${b.title}</div><div style="font-size:11px;color:var(--text-muted)">${b.desc}</div></div>`;t.classList.remove('hide');setTimeout(()=>t.classList.add('hide'),3500)}
function showModal(title,fields,onSave){const mc=document.getElementById('modal-container');let fh=fields.map(f=>`<div class="form-field"><label class="form-label">${f.label}</label>${f.type==='textarea'?`<textarea class="form-input" id="mf-${f.key}" placeholder="${f.ph||''}" rows="3"></textarea>`:`<input class="form-input" id="mf-${f.key}" placeholder="${f.ph||''}"/>`}</div>`).join('');mc.innerHTML=`<div class="modal-overlay" onclick="closeModal()"><div class="modal-card" onclick="event.stopPropagation()"><div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:20px"><div class="card-title">${title}</div><button onclick="closeModal()" style="width:32px;height:32px;border-radius:10px;border:1px solid var(--border-subtle);background:var(--bg-warm);cursor:pointer;font-size:14px;color:var(--text-muted);display:flex;align-items:center;justify-content:center;transition:.2s" onmouseover="this.style.background='var(--accent-coral-soft)'" onmouseout="this.style.background='var(--bg-warm)'">✕</button></div>${fh}<div style="display:flex;gap:10px"><button class="btn btn-jade" onclick="saveModal()">✓ Saqlash</button><button class="btn btn-ghost" onclick="closeModal()">Bekor</button></div></div></div>`;mc._fields=fields;mc._onSave=onSave}
function closeModal(){document.getElementById('modal-container').innerHTML=''}
function saveModal(){const mc=document.getElementById('modal-container'),v={};mc._fields.forEach(f=>{v[f.key]=document.getElementById('mf-'+f.key).value});mc._onSave(v);closeModal()}

/* ══════ DASHBOARD ══════ */
